### ISSUE TITLE
Review styling and branding across Leeds Cultural Engagement

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/leeds-schools-cultural-engagement#32]
A few things to pick up: 

- [ ] Review colours across the site - links to #31 
- [ ] Review fonts across the site - links to #30 
- [ ] Rename the site to 'Mapping Creative Education' links to #35 
- [ ] Add the Mapping Creative Education logo to the header 
- [x] Add a navigation menu to the header 
- [ ] Amend logo ordering in the footer
